### ISSUE TITLE
The loading for 2D NMR is too slow

### ISSUE THREAD

**Issue by baolanlequang** [NFDI4Chem/nmrium-react-wrapper#163]
Hi, we are facing the problem of 2D NMR loading so slowly. Do you have any idea or solution to deal with this?

We're using the wrapper v0.4.0. 

As you can see in the video, the original file is 13.9MB, but after we got data from NMRium, the `*.nmrium` file is around 58.7MB. Hence, the second loading is so slow.

The file that I used in the video is [SG-V4004 (15-36)_15.zip](https://github.com/NFDI4Chem/nmrium-react-wrapper/files/13203279/SG-V4004.15-36._15.zip)

https://github.com/NFDI4Chem/nmrium-react-wrapper/assets/9006482/e2922117-ce52-4604-806d-0b9571e4c36c

**Comment by hamed-musallam** [comment]
This is a result of the nmrium object you have saved. To address this issue, you need to perform mapping and filtering operations on the spectra objects, specifically removing the `data` and `originalData` properties from each spectrum object.

Actually, those objects have no need for them since you have the original files unless you need those data for further processing from your side.

**Comment by hamed-musallam** [comment]
On the other hand,  I believe there may be an issue in your implementation, as I've observed a delay in triggering the loading actions. Why? Is it because you process the files before triggering the loading action?

**Comment by CS76** [comment]
@baolanlequang have you managed to resolve this issue??

**Comment by baolanlequang** [comment]
Closed as it was resolved.
