### ISSUE TITLE
Can we have the option to chose the file format of preview image?

### ISSUE THREAD

**Issue by baolanlequang** [NFDI4Chem/nmrium-react-wrapper#34]
Currently, the preview image is `svg` format when calling `exportSpectraViewerAsBlob`. Do we have any option to get the `png` format or the other image formats?

**Comment by CS76** [comment]
We can enable this @baolanlequang; however, it would be ideal to do this at the parent application level because you might also want to chain additional operations, such as compression or adding annotations on the image. So giving the Blob will enable you to convert it to SVG and have the highest resolution possible for further operations.

**Comment by baolanlequang** [comment]
Yes, I know that. But it will be great if we have this option, at least with `png` format, because I see there is an option that allows users can export the image as `png` format.
![Screenshot from 2022-08-16 10-29-41](https://user-images.githubusercontent.com/9006482/184834599-3a739e78-156e-4d23-af7c-55d3d46e9b1e.png)

**Comment by CS76** [comment]
Currently handled on the server side with the SVG canvas handed over back by nmrium-wrapper to the parent application.
