### ISSUE TITLE
Suggestion: Provide an endpoint to query the data version

### ISSUE THREAD

**Issue by ptrxyz** [NFDI4Chem/nmrium-react-wrapper#62]
We realized that the public nmrium-wrapper instance at Jena is running on data version 3, the development container already implements version 4.
As of now, we can't properly check what data version the nmrium wrapper uses besides "looking at the returned data structure". This doesn't seem to be a very robust way of doing it especially in the long run, so we suggest to add an API call to let applications know what data version to expect.

**Comment by hamed-musallam** [comment]
@ptrxyz 

Can you clarify why you need to know the version of the data? , knowing the version number is important from our side for migration purposes.

you should store the version with data at your end otherwise we will not be able to manage the migration.

**Comment by hamed-musallam** [comment]
@CS76 

In case you want to migrate the data from your end without loading the data one more time  on NMRium it is possible too, we can provide an end to do the migration for you.

https://github.com/cheminfo/nmr-load-save/blob/881c1b9b348365e73a738b58f8e336fff5fec6a9/src/migration/MigrationManager.ts#L12

**Comment by hamed-musallam** [comment]
@ptrxyz @CS76 

We will still make changes to the nmrium structure and this is something we can not prevent at this stage but what we can do is provide an endpoint for data migration to solve this issue until we have a stable release

NMRium has a complex structure and for any changes we do to the data structure, we write a migration script to be sure nothing is broken.

so until we reach version 1.0.0 of NMRium the changes will happen from time to time,  simply because the NMRium evolves over time and most of the time we do the changes for three things, reduce complexity, add a new feature or fix bugs, or find a better structure

**Comment by CS76** [comment]
@hamed-musallam Thank you for clarifying this. So, until we have a stable data structure, it would be good if we could provide an easy way of mapping the nmrium-react-wrapper/nmrium version with the data version it supports for the developers. This should/could be provided on the repository readme document. Also, we can create a new event listener on nmrium-react-wrapper (action request: info) to return a similar response when requested by chemotion/nmrXiv.
